name: Build Mod

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Resize icon to 256x256
      run: |
        sudo apt-get install -y imagemagick
        convert icon.png -resize 256x256 icon.png

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Set up Android build tools
      run: |
        ANDROID_BUILD_TOOLS=$(ls -1 $ANDROID_HOME/build-tools | sort -V | tail -n 1)
        echo "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}" >> $GITHUB_PATH

    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew deploy

    - name: Delete old release if exists
      run: gh release delete v157.3 --yes || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release with jar
      run: gh release create v157.3 build/libs/*.jar --title "AutoDrill Reworked v157.3" --notes "Updated for Mindustry v157.3" --latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
